### PR TITLE
Make XML valid for cobertura-04 dtd

### LINKED ISSUE #5: Add Cobertura 04 support
Hello :)

I'm building a Lua project on VSTS and came across this issue: https://github.com/Microsoft/vsts-tasks/issues/3036. 

This PR fixed it in gcovr: https://github.com/gcovr/gcovr/pull/186/files

It'd be nice to support this new DTD schema from Cobertura (http://cobertura.sourceforge.net/xml/coverage-04.dtd).

### PR DESCRIPTION
**Pull request by biancarosa**
Closes #5.

# Description

Makes the XML generated valid against the new Cobertura schema, by adding:

 - branches-covered
 - branches-valid
 - complexity
 - lines-covered
 - lines-valid

into the coverage tag.

lines-covered and lines-valid are calculated with the sum of all packages, and the rest will remain zero.

also removes optional source tag. 

We just have to discuss if:

- Creating a new version (2.0) is the best option.
- This version breaks the XML against the (coverage-03.dtd)[http://cobertura.sourceforge.net/xml/coverage-03.dtd]. Are we supposed to keep backwards compatibility?

# How to test

Run the report after LuaCov and lint the XML against (this)[http://cobertura.sourceforge.net/xml/coverage-04.dtd] DTD.

`xmllint --dtdvalid coverage-04.dtd --noout cobertura.xml`

### CODE REVIEW

**Comment by britzl** [comment]
Thank you for the PR. It was quite some time ago that I created this project and I don't use it regularly anymore. I decided to do a minor structural change where I moved the bin and luacov folders from src into project root. I also created a tiny example so that I could test that the code still works (I guess writing some proper unit tests would be best, but for now there's at least an example that can be run to see that the project still spits out a report). Finally, I also updated the rockspec.

On to the question at hand: Should we break backwards compatibility with v3 or not? In general I'm all for upgrading, but what if someone is using a CI plugin that doesn't support v4? Could we perhaps make it an option when generating the report? It would add a bunch of conditionals, but it wouldn't be that bad or?

**Comment by britzl** [comment]
Thanks! Let's just merge and see if anyone complains!

**Comment by biancarosa** [comment]
@britzl I was trying to make it optional using a flag, but maybe if someone complains the person could use the old version, because it doesn't seem quite easy to add a flag because we are relying on the luacov reporter config file.

Thanks for merging it :heart:

**Comment by biancarosa** [comment]
@britzl can you push this version to luarocks? :)

**Comment by britzl** [comment]
I think I did: https://luarocks.org/modules/britzl/luacov-cobertura/1.1-0 Although I'm no LuaRocks expert so I might have done something wrong?

**Pull request merged**
